<?php

declare(strict_types=1);

namespace Jefferson49\Webtrees\Module\RepositoryHierarchyNamespace;

use Fisharebest\Webtrees\Fact;
use Fisharebest\Webtrees\Session;
use Fisharebest\Webtrees\Services\ModuleService;

/**
 * @var Fact        $fact
 * @var string|null $url
 */

$module_service = new ModuleService();
$repository_hierarchy = $module_service->findByName(RepositoryHierarchy::activeModuleName());

?>

<?php if ($fact->canEdit()) : ?>
    <div class="pt-2 wt-fact-edit-links">
        <?= view('edit/icon-fact-edit', ['fact' => $fact, 'url' => $url ?? null]) ?>
        <?= view('edit/icon-fact-copy', ['fact' => $fact]) ?>
        <?= view('edit/icon-fact-delete', ['fact' => $fact]) ?>

        <?php //Additionally show icon to paste source citations; only show for individual and family views?>
        <?php if (Session::has(RepositoryHierarchy::PREF_CITATION_GEDCOM . '_' . $fact->record()->tree()->id()) &&
                  boolval($repository_hierarchy->getPreference(RepositoryHierarchy::PREF_ENABLE_COPY_PASTE_CITATIONS, '0'))    ) : ?>
            <?php if (in_array($fact->record()->tag(), ['INDI', 'FAM'])) : ?>
                <?php //Dont show certain tags, where source citations are not allowed?>
                <?php if (!in_array($fact->tag(), [
                    'INDI:SOUR', 'INDI:NOTE', 'INDI:OBJE', 'INDI:CHAN', 'INDI:SUBM', 'INDI:ALIA', 'INDI:ANCI', 'INDI:DESI', 'INDI:RFN', 'INDI:AFN', 'INDI:RIN', 'INDI:REFN', 
                    'FAM:SOUR', 'FAM:NOTE', 'FAM:OBJE', 'FAM:NCHI', 'FAM:SUBM','FAM:CHAN', 'FAM:REFN', 'FAM:RIN',])) : ?>
                    <?= view(RepositoryHierarchy::viewsNamespace() . '::edit/icon-source-citation-paste', ['fact' => $fact]) ?>
                <?php endif ?>          
            <?php endif ?>
        <?php endif ?>   
    </div>
<?php endif ?>