<?php
 
namespace Jefferson49\Webtrees\Module\RepositoryHierarchyNamespace;

use Cissee\WebtreesExt\MoreI18N;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Repository;
use Fisharebest\Webtrees\Services\ModuleService;
use Fisharebest\Webtrees\Session;
use Fisharebest\Webtrees\View;
use Matriphe\ISO639\ISO639;

use function date;

/**
 * @var string					$title
 * @var string					$language_tag
 * @var CallNumberCategory      $root_category
 * @var Repository				$repository
 */

?>
<!DOCTYPE HTML>
<html lang="<?= $language_tag	?>">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8">
		<title><?= $title ?></title>

		<style>
			.finding-aid-body {
				font-size:10pt;
				font-family: Arial,Verdana,sans-serif;
			}
			.finding-aid-table {
				width: 100%; 
				padding: 5px;
				vertical-align: top;
				border: none; 
			} 
			.finding-aid-table-caption {
				font-weight: 700; 
				background-color: #c0c0c0; 
				border: 1px solid black; 
				padding-left: 5px;
				padding-top: 20px;
				padding-bottom: 20px;
				text-align: left;
			}
			.finding-aid-table-foot {
				height: 10px;
				border: 1px solid black; 
			}
			.finding-aid-first-row {
				border-spacing: 0px;
				padding: 0px;
			}
			.finding-aid-last-row {
				border: 1px solid black;
				padding: 1px;
			}
			.finding-aid-first-column {
				width: 100px;
			}
			.finding-aid-last-column {
				width: 160px;
			}
			td {
				vertical-align: top;	
			}
			.tab { 
				display:inline-block; 
				margin-left: 40px; 
			}
		</style>
	</head>
	<body class="finding-aid-body">
		<h1><?= $title ?></h1>
		<p><?= I18N::translate('Generated on: ') . date('Y-m-d') ?></p>

		<?php $iso_table = new ISO639 ?>
        <?php $language = $iso_table->nativeByCode1(Session::get('language')) ?>
		<p><?= I18N::translate('Language of description: ') . $language ?></p>

		<h4><?= MoreI18N::xlate('Repository') ?></h4>
		<p><?= $repository->fullName() ?></p>
		<?php $address_lines = Functions::getRepositoryAddressLines($repository) ?>
		<?php if (!empty($address_lines)) : ?>
			<?php foreach($address_lines as $line) : ?>
				<p><?= $line?></p>
			<?php endforeach ?>
		<?php endif ?>

		<?php foreach($repository->facts() as $fact) : ?>
			<?php if ($fact->tag() === 'REPO:ADDR') : ?>
				<?= view('fact', ['fact' => $fact, 'record' => $repository]) ?>
			<?php endif ?>
		<?php endforeach ?>

		<h2><?= I18N::translate('Table of contents') ?></h2>
		<?= view(RepositoryHierarchy::MODULE_NAME . '::table-of-contents', [
            'category'              => $root_category,
            'is_root_category'      => true,
            ]) ?>

		<h2><?= I18N::translate('List of sources') ?></h2>
		<?= view(RepositoryHierarchy::MODULE_NAME . '::category-html', [
			'category' 			=> $root_category,
			'repository' 		=> $repository,
			'is_root_category'	=> true,
			]) ?>
	</body>
</html>