<?php
 
namespace Jefferson49\Webtrees\Module\RepositoryHierarchyNamespace;

use Cissee\WebtreesExt\MoreI18N;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Repository;
use Fisharebest\Webtrees\Services\ModuleService;
use Fisharebest\Webtrees\Session;
use Fisharebest\Webtrees\View;
use Matriphe\ISO639\ISO639;

use function date;

/**
 * @var string								$title
 * @var string								$language_tag
 * @var CallNumberCategory      			$root_category
 * @var \Fisharebest\Webtrees\Repository	$repository
 */

?>
<!DOCTYPE HTML>
<html lang="<?= $language_tag	?>">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8">
		<title><?= $title ?></title>

		<style>
			.finding-aid-body {
				font-size:10pt;
				font-family: Arial,Verdana,sans-serif;
			}
			.finding-aid-table {
				width: 100%; 
				padding: 5px;
				vertical-align: top;
				border: none; 
			} 
			.finding-aid-table-caption {
				font-weight: 400; 
				background-color: #c0c0c0; 
				border-color: #c0c0c0;
				outline: 1px solid black;
				padding-left: 5px;
				padding-top: 20px;
				padding-bottom: 20px;
				text-align: left;
			}		
			.finding-aid-table-foot {
				height: 10px;
				border: 1px solid black; 
			}
			.finding-aid-table-first-row {
				border-spacing: 0px;
				padding: 0px;
			}
			.finding-aid-table-last-row {
				border: 1px solid black;
				padding: 1px;
			}
			.finding-aid-table-first-column {
				width: 100px;
			}
			.finding-aid-table-last-column {
				width: 160px;
			}
			td {
				vertical-align: top;	
			}

		</style>
	</head>
	<body class="finding-aid-body">
		<h1><?= $title ?></h1>
		<p><?= I18N::translate('Generated on') . ': ' . date('Y-m-d') ?></p>

		<?php $iso_table = new ISO639 ?>
        <?php $language = $iso_table->nativeByCode1(Session::get('language')) ?>
		<p><?= I18N::translate('Language of description') . ': ' . $language ?></p>

		<h3><?= MoreI18N::xlate('Repository') ?></h3>
		<p><?= $repository->fullName() ?></p>
		<p>
			<b><?= MoreI18N::xlate('Address') ?>:</b><br>
			<?php $address_lines = Functions::getRepositoryAddressLines($repository) ?>
			<?php foreach($address_lines as $line) : ?>
				<?= $line?><br>
			<?php endforeach ?>
		</p>
		<h2><?= I18N::translate('Table of contents') ?></h2>
		<?= view(RepositoryHierarchy::MODULE_NAME . '::table-of-contents', [
            'category'              => $root_category,
            'is_root_category'      => true,
            ]) ?>

		<h2><?= I18N::translate('List of sources') ?></h2>
		<?= view(RepositoryHierarchy::MODULE_NAME . '::category-html', [
			'category' 			=> $root_category,
			'repository' 		=> $repository,
			'is_root_category'	=> true,
			]) ?>
	</body>
</html>