<?php

declare(strict_types=1);

namespace Jefferson49\Webtrees\Module\RepositoryHierarchy;

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;
use Jefferson49\Webtrees\Internationalization\MoreI18N;

/**
	* @var Tree                $tree
	* @var string              $title
	* @var RepositoryHierarchy $repository_hierarchy
	* @var string              $delimiter_expression
	* @var string              $error
	* @var string              $command
	*/

?>

<?php if ($error != '') : ?>
	<div class="alert alert-danger">
		<?= $error ?>
	</div>
<?php endif ?>

<h2 class="wt-page-title">
	<?php //Do not escape, because it is already escaped in the method  ?>
	<?= $repository_hierarchy->getListTitle($repository_hierarchy->getRepository()) ?>
</h2>

<form method="post" action="<?= e(route(RepositoryHierarchy::class, [
		'tree'		=> $tree->name(),
		'xref'		=> $repository_hierarchy->getRepositoryXref(),
		])) ?>"
	class="wt-page-options wt-page-options-ancestors-chart d-print-none">

	<div class="row">
		<label class="col-sm-3 col-form-label wt-page-options-label" for="xref">
			<?= MoreI18N::xlate('Repository') ?>
		</label>
		<div class="col-sm-9 wt-page-options-value">
			<?= view('components/select-repository', [
				'name' => 'xref',
				'repository' => $repository_hierarchy->getRepository(),
				'tree' => $tree,
				'required' => true]) ?>
		</div>
	</div>

	<div class="row">
		<label class="col-sm-3 col-form-label wt-page-options-label" for="delimiter_expression">
			<?= I18N::translate('Delimiter Expression for Call Numbers') ?>
			<a href="#" data-bs-toggle="modal" data-bs-backdrop="static" data-bs-target="#wt-ajax-modal" data-wt-href="<?= e(route(RepositoryHierarchyHelpTexts::class, ['topic' => 'Delimiter Expression'])) ?>">
				<?= view('icons/spacer') ?>
				<?php if (boolval($repository_hierarchy->getPreference($repository_hierarchy::PREF_SHOW_HELP_ICON, '1'))) : ?>
					<?= view('icons/help') ?>
				<?php endif ?>
				<?php if (boolval($repository_hierarchy->getPreference($repository_hierarchy::PREF_SHOW_HELP_LINK, '1'))) : ?>
					<?= I18N::translate('Help') ?>
				<?php endif ?>
			</a>
		</label>
		<div class="col-sm-9 wt-page-options-value">
			<input class="form-control" id="delimiter_expression" name="delimiter_expression" type="text" value="<?= e($delimiter_expression) ?>" required="required">
		</div>
	</div>

	<div class="row">
		<label class="col-sm-3 col-form-label wt-page-options-label" for="view">
			<?= I18N::translate('View and load/save options') ?>
		</label>
		<div class="col-sm-9 wt-page-options-value">
			<input class="btn btn-primary" type="submit" value="<?= I18N::translate('view') ?>">
			<?= view('icons/spacer') ?>
			<?= view('components/radios-inline', [
				'name' => 'command',
				'options' => $repository_hierarchy->getLoadSaveOptions(),
				'selected' => RepositoryHierarchy::CMD_NONE,
				]) ?>
		</div>

	</div>

	<?= csrf_field() ?>
</form>

<?php if ($delimiter_expression !== '') : ?>
	<form method="post" action="<?= e(route(RepositoryHierarchy::class, [
							'tree'                  => $tree->name(),
							'xref'                  => $repository_hierarchy->getRepositoryXref(),
							'delimiter_expression'  => $delimiter_expression,
							'command'               => RepositoryHierarchy::CMD_DOWNLOAD,
							])) ?>"
			class="wt-page-options wt-page-options-ancestors-chart d-print-none">
		<div class="row">
			<label class="col-sm-3 col-form-label wt-page-options-label">
				<?= MoreI18N::xlate('Download') ?>
			</label>
			<div class="col-sm-9 wt-page-options-value">
				<input class="btn btn-secondary" type="submit" value="<?= MoreI18N::xlate('Download') ?>">
				<?= view('icons/spacer') ?>
				<?= view('components/radios-inline', [
					'name' => 'download_command',
					'options' => DownloadService::getDownloadOptions(DownloadService::DOWNLOAD_OPTION_ALL),
					'selected' => DownloadService::DOWNLOAD_OPTION_HTML,
				]) ?>
				<?= view('icons/spacer') ?>
				<a href="#" data-bs-toggle="modal" data-bs-backdrop="static" data-bs-target="#wt-ajax-modal"
							data-wt-href="<?= e(route(XmlExportSettingsModal::class, [
								'tree'                  => $tree->name(),
								'xref'                  => $repository_hierarchy->getRepositoryXref(),
								'delimiter_expression'  => $delimiter_expression,
								])) ?>">
					<input class="btn btn-secondary" type="submit" value="<?= I18N::translate('EAD XML settings') ?>">
				</a>
			</div>
		</div>

		<?= csrf_field() ?>
	</form>
<?php endif ?>

<?php if (($delimiter_expression !=='') && ($error === '')) : ?>
	<div class="wt-ajax-load wt-page-content wt-chart wt-chart-ancestors">
		<?php $categories = Functions::getCollectionForArray($repository_hierarchy->getRootCategory()->getSubCategories()) ?>
		<?php foreach ($categories as $sub_category) : ?>
			<?= view(RepositoryHierarchy::viewsNamespace() . '::tree', [
					'repository_xref'                   => $repository_hierarchy->getRepositoryXref(),
					'tree_name'                         => $repository_hierarchy->getTree()->name(),
					'author_of_source'                  => $repository_hierarchy->author_of_source,
					'call_number_of_source'             => $repository_hierarchy->call_number_of_source,
					'truncated_call_number_of_source'   => $repository_hierarchy->truncated_call_number_of_source,
					'date_range_text_of_source'         => $repository_hierarchy->date_range_text_of_source,
					'category'                          => $sub_category,
					'callNumberCategoryTitleService'    => $repository_hierarchy->getCallNumberCategoryTitleService(),
					'PREF_SHOW_CATEGORY_TITLE'          => $repository_hierarchy->getPreference($repository_hierarchy::PREF_SHOW_CATEGORY_TITLE, '0'),
					'PREF_SHOW_DATE_RANGE_FOR_CATEGORY' => $repository_hierarchy->getPreference($repository_hierarchy::PREF_SHOW_DATE_RANGE_FOR_CATEGORY, '0'),
					'PREF_SHOW_CATEGORY_LABEL'          => $repository_hierarchy->getPreference($repository_hierarchy::PREF_SHOW_CATEGORY_LABEL, '1'),
					'PREF_SHOW_TRUNCATED_CATEGORY'      => $repository_hierarchy->getPreference($repository_hierarchy::PREF_SHOW_TRUNCATED_CATEGORY, '1'),
					'PREF_SHOW_TRUNCATED_CALL_NUMBER'   => $repository_hierarchy->getPreference($repository_hierarchy::PREF_SHOW_TRUNCATED_CALL_NUMBER, '1'),
					'PREF_ALLOW_RENAME'                 => $repository_hierarchy->getPreference($repository_hierarchy::PREF_ALLOW_RENAME, '1'),
					'PREF_ALLOW_NEW_SOURCE'             => $repository_hierarchy->getPreference($repository_hierarchy::PREF_ALLOW_NEW_SOURCE, '1'),
					'PREF_SHOW_TITLE'                   => $repository_hierarchy->getPreference($repository_hierarchy::PREF_SHOW_TITLE, '1'),
					'PREF_SHOW_XREF'                    => $repository_hierarchy->getPreference($repository_hierarchy::PREF_SHOW_XREF, '1'),
					'PREF_SHOW_AUTHOR'                  => $repository_hierarchy->getPreference($repository_hierarchy::PREF_SHOW_AUTHOR, '1'),
					'PREF_SHOW_DATE_RANGE'              => $repository_hierarchy->getPreference($repository_hierarchy::PREF_SHOW_DATE_RANGE, '1'),
					'trans_Call_Number_Category'        => I18N::translate('Call Number Category'),
					'trans_Rename'                      => I18N::translate('Rename'),
					'trans_Add_new_source'              => I18N::translate('Add new source'),
					'trans_Author'                      => I18N::translate('Author'),
					'xlate_Title'                       => MoreI18N::xlate('Title'),
					'xlate_Date_range'                  => MoreI18N::xlate('Date range'),
					]) ?>
		<?php endforeach ?>
	</div>
<?php endif ?>

<?= view('modals/ajax') ?>
