<?php

namespace Jefferson49\Webtrees\Module\RepositoryHierarchyNamespace;

use Fisharebest\Webtrees\HelpText;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Repository;
use Fisharebest\Webtrees\Tree;
use Fisharebest\Webtrees\View;

/**
 * @var Tree      		 	$tree
 * @var string      		$title
 * @var RepositoryHierarchy	$repository_hierarchy
 * @var string      		$delimiter_expression
 * @var string             	$error
 * @var string             	$command 
 * @var string             	$xml_command 
 */
 
?>

<?php if ($error != '' ) : ?>
	<div class="alert alert-danger">
		<?= $error ?>
	</div>
<?php endif ?>

<h2 class="wt-page-title">
	<?= $repository_hierarchy->getListTitle($repository_hierarchy->getRepository()) ?>
</h2>

<form method="post" class="wt-page-options wt-page-options-ancestors-chart d-print-none">

	<div class="row">
		<label class="col-sm-3 col-form-label wt-page-options-label" for="xref">
			<?= I18N::translate('Repository') ?>
		</label>
		<div class="col-sm-9 wt-page-options-value">
			<?= view('components/select-repository', [
				'name' => 'xref', 
				'repository' => $repository_hierarchy->getRepository(), 
				'tree' => $tree, 
				'required' => true]) ?>
		</div>
	</div>

	<div class="row">
		<label class="col-sm-3 col-form-label wt-page-options-label" for="delimiter_expression">
			<?= I18N::translate('Delimiter Expression for Call Numbers') ?>
			<a href="#" data-bs-toggle="modal" data-bs-backdrop="static" data-bs-target="#wt-ajax-modal" data-wt-href="<?= e(route(RepositoryHierarchyHelpTexts::class, ['topic' => 'Delimiter Expression'])) ?>">
				<?= view('icons/spacer') ?>
				<?php if (boolval($repository_hierarchy->getPreference($repository_hierarchy::PREF_SHOW_HELP_ICON, '1'))) : ?>							
					<?= view('icons/help') ?>
				<?php endif ?>			
				<?php if (boolval($repository_hierarchy->getPreference($repository_hierarchy::PREF_SHOW_HELP_LINK, '1'))) : ?>							
					<?= I18N::translate('Help') ?>
				<?php endif ?>			
			</a>
		</label>
		<div class="col-sm-9 wt-page-options-value">
			<input class="form-control" id="delimiter_expression" name="delimiter_expression" type="text" value="<?= e($delimiter_expression) ?>" required="required">
		</div>
	</div>

	<fieldset class="row mb-3">
		<legend class="col-form-label col-sm-3 wt-page-options-label">
			<?= I18N::translate('Options') ?>
		</legend>

		<div class="col-sm-9 wt-page-options-value">
			<?= view('components/radios-inline', [
				'name' => 'command', 
				'options' => $repository_hierarchy->getLoadSaveOptions(), 
				'selected' => RepositoryHierarchy::CMD_NONE,
				]) ?>
		</div>
	</fieldset>	
	
	<div class="row mb-3">
		<div class="col-form-label col-sm-3 wt-page-options-label"><?= I18N::translate('View/Download') ?></div>
			<div class="col-sm-9 wt-page-options-value">			
				<input class="btn btn-primary" type="submit" value="<?= I18N::translate('view') ?>">
				<a href="<?= e(route(RepositoryHierarchy::class, [
						'tree'                              => $tree->name(),
						'xref'								=> $repository_hierarchy->getRepositoryXref(),
						'delimiter_expression'              => $delimiter_expression,
						'command'                           => RepositoryHierarchy::CMD_DOWNLOAD_XML,
						])) ?>" 
					class="btn btn-secondary">
					<?= I18N::translate('Download EAD XML') ?>
				</a>
				<a href="#" data-bs-toggle="modal" data-bs-backdrop="static" data-bs-target="#wt-ajax-modal" 
							data-wt-href="<?= e(route(XmlExportSettingsModal::class, [
								'tree' 		=> $tree->name(),
								'xref' 		=> $repository_hierarchy->getRepositoryXref(),
								'command'	=> RepositoryHierarchy::CMD_NONE,
								])) ?>">
					<input class="btn btn-secondary" type="submit" value="<?= I18N::translate('EAD XML settings') ?>">
				</a>
				<?php if(boolval($repository_hierarchy->getPreference(RepositoryHierarchy::PREF_ALLOW_ADMIN_XML_SETTINGS, '0'))) : ?>
					<a href="#" data-bs-toggle="modal" data-bs-backdrop="static" data-bs-target="#wt-ajax-modal" 
							data-wt-href="<?= e(route(XmlExportSettingsModal::class, [
								'tree' 		=> $tree->name(), 
								'xref' 		=> $repository_hierarchy->getRepositoryXref(),
								'command'	=> RepositoryHierarchy::CMD_LOAD_ADMIN_XML_SETTINGS,
								])) ?>">
						<input class="btn btn-secondary" type="submit" value="<?= I18N::translate('EAD XML settings (from admin)') ?>">
					</a>
				<?php endif ?>		
			</div>
		</div>
	</div>					

	<?= csrf_field() ?>
</form>

<?php if (($delimiter_expression !=='') && ($error === '')) : ?>
	<div class="wt-ajax-load wt-page-content wt-chart wt-chart-ancestors">
		<?php foreach ($repository_hierarchy->getRootCategory()->getSubCategories() as $sub_category) : ?>
			<?= view($repository_hierarchy->name() . '::tree', [
					'repository_hierarchy' => $repository_hierarchy, 
					'category' => $sub_category,
					]) ?>
		<?php endforeach ?>	
	</div>
<?php endif ?>

<?= view('modals/ajax') ?>
