<?php
 
namespace Jefferson49\Webtrees\Module\RepositoryHierarchyNamespace;

use Cissee\WebtreesExt\MoreI18N;
use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\View;

/**
 * @var  string		$title
 * @var  bool		$show_category_label
 * @var  bool		$show_help_icon
 * @var  bool		$show_help_link
 * @var  bool		$show_category_expanded
 * @var  bool		$show_truncated_call_number
 * @var  bool		$show_truncated_category
 * @var  bool		$show_title
 * @var  bool		$show_xref
 * @var  bool		$show_author
 * @var  bool		$show_date_range
 * @var  bool		$allow_admin_delimiter
 * @var  bool		$show_source_facts_in_citations
 * @var  bool		$show_finding_aid_address
 * @var  bool		$show_finding_aid_wt_links
 * @var  bool		$show_finding_aid_toc
 * @var  bool		$show_finding_aid_toc_links
 * @var  bool		$allow_admin_xml_settings
 * @var  bool		$use_meta_repositories
 * @var  bool		$show_atom_links
 * @var  string		$atom_slug
 * @var  string		$atom_base_url
 * @var  string		$atom_repositories
 */

?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => MoreI18N::xlate('Control panel'), $title]]) ?>

<h1><?= $title ?></h1>

<div class="row mb-3">
	<form method="post">
		<?= csrf_field() ?>
		<input type="hidden" name="save" id="save" value="1">

        <div class="row mb-3 justify-content-between m-0">

            <div class="row"><?= view('icons/spacer') ?></div> 
            <h3><?= I18N::translate('Settings for Repository Hierarchy list') ?></h3>
            <div class="row">
                <?= view('components/checkbox', ['label' => I18N::translate('Show label before call number category.'), 'name' => RepositoryHierarchy::PREF_SHOW_CATEGORY_LABEL, 'checked' => $show_category_label]) ?>
			</div> 
            <div class="row">
                <?= view('components/checkbox', ['label' => I18N::translate('Show help icon after label for delimiter expression.'), 'name' => RepositoryHierarchy::PREF_SHOW_HELP_ICON, 'checked' => $show_help_icon]) ?>
			</div> 
            <div class="row">
                <?= view('components/checkbox', ['label' => I18N::translate('Show help link after label for delimiter expression.'), 'name' => RepositoryHierarchy::PREF_SHOW_HELP_LINK, 'checked' => $show_help_link]) ?>
			</div> 
           <div class="row">
                <?= view('components/checkbox', ['label' => I18N::translate('Use truncated categories. The call number categories will be truncated and shown without the trunk.'), 'name' => RepositoryHierarchy::PREF_SHOW_TRUNCATED_CATEGORY, 'checked' => $show_truncated_category]) ?>
			</div> 
           <div class="row">
                <?= view('components/checkbox', ['label' => I18N::translate('Use truncated call numbers. The call numbers will be truncated and shown without call number category.'), 'name' => RepositoryHierarchy::PREF_SHOW_TRUNCATED_CALL_NUMBER, 'checked' => $show_truncated_call_number]) ?>
			</div> 
           <div class="row">
                <?= view('components/checkbox', ['label' => I18N::translate('Show the title of the sources.'), 'name' => RepositoryHierarchy::PREF_SHOW_TITLE, 'checked' => $show_title]) ?>
			</div>
            <div class="row">
                <?= view('components/checkbox', ['label' => I18N::translate('Show the XREF of the sources.'), 'name' => RepositoryHierarchy::PREF_SHOW_XREF, 'checked' => $show_xref]) ?>
			</div>
            <div class="row">
                <?= view('components/checkbox', ['label' => I18N::translate('Show the author of the sources.'), 'name' => RepositoryHierarchy::PREF_SHOW_AUTHOR, 'checked' => $show_author]) ?>
			</div>			
            <div class="row">
                <?= view('components/checkbox', ['label' => I18N::translate('Show the date range of the sources.'), 'name' => RepositoryHierarchy::PREF_SHOW_DATE_RANGE, 'checked' => $show_date_range]) ?>
            </div>
            <div class="row">
                <?= view('components/checkbox', ['label' => I18N::translate('Allow users to load stored delimiter expressions from administrator.'), 'name' => RepositoryHierarchy::PREF_ALLOW_ADMIN_DELIMITER, 'checked' => $allow_admin_delimiter]) ?>
            </div>

            <div class="row"><?= view('icons/spacer') ?></div> 
            <h3><?= I18N::translate('Settings for source citations') ?></h3>
            <div class="row">
                <?= view('components/checkbox', ['label' => I18N::translate('Show additional source facts (REPO, REPO:CALN, REFN, NOTE) within source citations.'), 'name' => RepositoryHierarchy::PREF_SHOW_SOURCE_FACTS_IN_CITATIONS, 'checked' => $show_source_facts_in_citations]) ?>
            </div>

            <div class="row"><?= view('icons/spacer') ?></div> 
            <h3><?= I18N::translate('Settings for finding aid exports') ?></h3>
            <div class="row">
                <?= view('components/checkbox', ['label' => I18N::translate('Include repository address within finding aid export.'), 'name' => RepositoryHierarchy::PREF_SHOW_FINDING_AID_ADDRESS, 'checked' => $show_finding_aid_address]) ?>
            </div>            
            <div class="row">
                <?= view('components/checkbox', ['label' => I18N::translate('Include links to webtrees sources within finding aid export.'), 'name' => RepositoryHierarchy::PREF_SHOW_FINDING_AID_WT_LINKS, 'checked' => $show_finding_aid_wt_links]) ?>
            </div>            
            <div class="row">
                <?= view('components/checkbox', ['label' => I18N::translate('Include table of contents within finding aid export.'), 'name' => RepositoryHierarchy::PREF_SHOW_FINDING_AID_TOC, 'checked' => $show_finding_aid_toc]) ?>
            </div>
            <div class="row">
                <?= view('components/checkbox', ['label' => I18N::translate('Show links within table of contents in finding aid export (not available for PDF export).'), 'name' => RepositoryHierarchy::PREF_SHOW_FINDING_AID_TOC_LINKS, 'checked' => $show_finding_aid_toc_links]) ?>
            </div>

            <div class="row"><?= view('icons/spacer') ?></div> 
            <h3><?= I18N::translate('Settings for EAD XML exports') ?></h3>
            <div class="row">
                <?= view('components/checkbox', ['label' => I18N::translate('Allow users to load stored XML settings from administrator.'), 'name' => RepositoryHierarchy::PREF_ALLOW_ADMIN_XML_SETTINGS, 'checked' => $allow_admin_xml_settings]) ?>
            </div>

            <div class="row"><?= view('icons/spacer') ?></div> 
            <h3><?= I18N::translate('Settings for Meta Repositories') ?></h3>
            <div class="row">
                <?= view('components/checkbox', ['label' => I18N::translate('Use Meta Repositories.'), 'name' => RepositoryHierarchy::PREF_USE_META_REPOSITORIES, 'checked' => $use_meta_repositories]) ?>
            </div>            

            <div class="row"><?= view('icons/spacer') ?></div> 
            <h3><?= I18N::translate('Settings for linking to external archive management tools') ?></h3>
            <div class="row">            
                <?= I18N::translate('The following settings apply if AtoM (https://www.accesstomemory.org) is used as an external archive management system.') ?>
            </div>                
            <div class="row">
                <p></p>
                <?= view('components/checkbox', ['label' => I18N::translate('Show link to AtoM records within source citations').'.', 'name' => RepositoryHierarchy::PREF_SHOW_ATOM_LINKS, 'checked' => $show_atom_links]) ?>
            </div> 
            <div class="row">
                <p></p>
                <?= I18N::translate('Settings for the creation of AtoM REST links ("AtoM slugs"), which can be used to link a webtrees source citation to the source view in an external AtoM archive management system. Only applies if the option "%s" is activated.', I18N::translate('Show link to AtoM records within source citations')) ?>

                <div class="row">
                <p></p>
                <?= view('components/radios', [
                    'name' => 'atom_slug', 
                    'selected' => $atom_slug,
                    'options' => [
                        RepositoryHierarchy::PREF_ATOM_SLUG_CALL_NUMBER => I18N::translate('Use call numbers to create AtoM REST links ("AtoM slugs")'),
                        RepositoryHierarchy::PREF_ATOM_SLUG_TITLE => I18N::translate('Use source titles to create AtoM REST links ("AtoM slugs")'),
                        ],
                    ]) ?>
            </div>            
            <div class="row">
                <label class="col-sm-3 col-form-label wt-page-options-label" for="atom_base_url">
                    <?= I18N::translate('Base URL for AtoM') ?>
                </label>
                <div class="col-sm-9 wt-page-options-value">
                    <input class="form-control" id="atom_base_url" name="atom_base_url" type="text" value="<?= e($atom_base_url) ?>">
                </div>
            </div>
            <div class="row">
                <label class="col-sm-3 col-form-label wt-page-options-label" for="atom_repositories">
                    <?= I18N::translate('Repositories, for which AtoM linking is used.') ?>
                </label>    			
                <div class="col-sm-9 wt-page-options-value">
	    			<input class="form-control" id="atom_repositories" name="atom_repositories" type="text" value="<?= e($atom_repositories) ?>">
			    </div>
                <p><?= I18N::translate('Format treename:xref. A list of several entries can be separated by comma, e.g. "my_tree:X1765,my_tree:X2987"') ?></p>
            </div>
        </div>
			
        <div class="col">
            <p></p>
            <button type="submit" class="btn btn-primary">
                <?= view('icons/save') ?>
                <?= I18N::translate('save') ?>
            </button>
        </div>
    </form>	
</div>

<?php View::push('javascript') ?>
<script>
    $('#select-all-1').change(function(e) {
        if (e.currentTarget.checked) {
            $('.mb-3 .row').find('input[type="checkbox"]').prop('checked', true);
        } else {
            $('.mb-3 .row').find('input[type="checkbox"]').prop('checked', false);
        }
    });
</script>
<?php View::endpush() ?>