<?php

namespace Jefferson49\Webtrees\Module\RepositoryHierarchyNamespace;

use Cissee\WebtreesExt\MoreI18N;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Registry;
use Fisharebest\Webtrees\Services\ModuleService;
use Fisharebest\Webtrees\Source;

/**
 * @var \Fisharebest\Webtrees\Tree $tree
 * @var Source $source
 */

$module_service = new ModuleService();
$repository_hierarchy = $module_service->findByName(RepositoryHierarchy::activeModuleName());
$atom_repositories = explode(',', $repository_hierarchy->getPreference(RepositoryHierarchy::PREF_ATOM_REPOSITORIES, ''));
$media_objects_labels_of_source = [];

?> 
 
<?php $facts = $source->facts() ?>
<?php foreach ($facts as $fact) : ?>

	<?php $element = Registry::elementFactory()->make($fact->tag()) ?>

	<?php if ($fact->tag() === 'SOUR:REPO') : ?>
		<?php $xref = str_replace('@', '', $fact->value()) ?>
		<?php $repository = Registry::repositoryFactory()->make($xref, $tree) ?>
		<?php $caln_string = $fact->attribute('CALN') ?>
		<?php $caln_element = Registry::elementFactory()->make('SOUR:REPO:CALN') ?>
		<?php $show_atom_links = ($repository_hierarchy->getPreference(RepositoryHierarchy::PREF_ATOM_BASE_URL, '') !== '') &&
									(boolval($repository_hierarchy->getPreference(RepositoryHierarchy::PREF_SHOW_ATOM_LINKS, '0'))) &&
									(in_array($tree->name() . ':' . $xref, $atom_repositories)) ?>

		<?php if (boolval($repository_hierarchy->getPreference(RepositoryHierarchy::PREF_SHOW_SOURCE_FACTS_IN_CITATIONS, '0'))) : ?>
			<?php if ($caln_string === '' && !$show_atom_links) : ?>
				<?php //Do not escape, because it is already escaped in the method  ?>
				<?= $element->labelValue(strtr($fact->value(), ["\r" => "\n"]), $tree) ?>
			<?php else : ?>
				<?php $id = Registry::idFactory()->id() ?>
				<?php $expanded = boolval($repository_hierarchy->getPreference(RepositoryHierarchy::PREF_EXPAND_REPOS_IN_CITATIONS, '0')) ?>
				<div>
					<button type="button" class="btn btn-text p-0" href="#<?= e($id) ?>" data-bs-toggle="collapse" aria-controls="<?= e($id) ?>" aria-expanded="<?= $expanded ? 'true' : 'false' ?>">
						<?= view('icons/expand') ?>
						<?= view('icons/collapse') ?>
					</button>

					<?php $label = '<span class="label">' . MoreI18N::xlate('Repository') . '</span>' ?>
					<?php $value = '<span class="field" dir="auto"><a href="' . e($repository->url()) . '">' . $repository->fullName() . '</a></span>' ?>
					<?= MoreI18N::xlate('%1$s: %2$s', $label, $value) ?>
				</div>
				<div id="<?= e($id) ?>" class="ps-4 collapse <?= $expanded ? 'show' : '' ?>">
					<?php if (boolval($repository_hierarchy->getPreference(RepositoryHierarchy::PREF_SHOW_SOURCE_FACTS_IN_CITATIONS, '0'))) : ?>
						<?php //Do not escape, because it is already escaped in the method  ?>
						<?= $caln_element->labelValue(strtr($caln_string, ["\r" => "\n"]), $tree) ?>
					<?php endif ?>
					<?php if ($show_atom_links) : ?>
						<?= view(RepositoryHierarchy::viewsNamespace() . '::atom-links', ['tree' => $tree, 'source' => $source, 'caln_string' => $caln_string]) ?>					
					<?php endif ?>					
				</div>
			<?php endif ?>
		<?php endif ?>
	<?php elseif ($fact->tag() === 'SOUR:OBJE') : ?>
		<?php $element = Registry::elementFactory()->make('SOUR:OBJE') ?>
		<?php array_push($media_objects_labels_of_source, $element->labelValue(strtr($fact->value(), ["\r" => "\n"]), $tree)) ?>
	<?php endif ?>
<?php endforeach ?>

<?php //Show all media objects of the source ?>
<?php if (	boolval($repository_hierarchy->getPreference(RepositoryHierarchy::PREF_SHOW_SOURCE_MEDIA_IN_CITATIONS, '0')) 
			&& sizeof($media_objects_labels_of_source) > 0) : ?>
	<?php $id = Registry::idFactory()->id() ?>
	<?php $expanded = false ?>
	<div>
		<button type="button" class="btn btn-text p-0" href="#<?= e($id) ?>" data-bs-toggle="collapse" aria-controls="<?= e($id) ?>" aria-expanded="<?= $expanded ? 'true' : 'false' ?>">
			<?= view('icons/expand') ?>
			<?= view('icons/collapse') ?>
		</button>

		<?php $label = '<span class="label">' .I18N::translate('Media objects of source') . '</span>' ?>
		<?php $value = '' ?>
		<?= MoreI18N::xlate('%1$s: %2$s', $label, $value) ?>
	</div>
	<div id="<?= e($id) ?>" class="ps-4 collapse <?= $expanded ? 'show' : '' ?>">
		<?php foreach ($media_objects_labels_of_source as $label) : ?>
			<?php //Do not escape, because it is already escaped in the label method  ?>
			<?= $label ?>
		<?php endforeach ?>
	</div>
<?php endif ?>
