<style>
    table {
        font-size: 10pt;
        width: 100%; 
        border-spacing: 2px;
    }
    tr.caption {
        font-weight: 700; 
        background-color: #c0c0c0; 
        border: 1px solid black; 
        text-align: left;
        valign: middle;
    }
    td.first_column {
        width: 80px;
    }
    td.last_column {
        width: 120px;
    }
</style>

<style>
			.finding-aid-body {
				font-size:10pt;
			}
			.finding-aid-table {
				width: 100%; 
				border-spacing: 2px;
				padding: 3px;
			} 
			.finding-aid-table-caption {
				font-weight: 700; 
				background-color: #c0c0c0; 
				border: 1px solid black; 
				text-align: left;
			}
			.finding-aid-first-row {
				border-spacing: 0px;
				padding: 0px;
			}
			.finding-aid-last-row {
				border: 1px solid black;
				border-spacing: 1px;
				padding: 1px;
			}
			.finding-aid-first_column {
				width: 80px;
			}
			.finding-aid-last_column {
				width: 160px;
			}
		</style>