<?php

namespace Jefferson49\Webtrees\Module\RepositoryHierarchy;

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Repository;
use Fisharebest\Webtrees\View;
use Illuminate\Support\Collection;

/**
 * @var CallNumberCategory  $category
 * @var RepositoryHierarchy $repository_hierarchy
 * @var bool                $is_root_category
 * @var bool                $show_links
 * @var bool                $show_titles
 */

?>

<?php if (!$is_root_category) : ?>
    <ul>
        <li>
            <?php if ($show_links) : ?>
                <a href="#<?= e($category->getId()) ?>"><?= e($category->getFrontEndName()) ?></a>
            <?php else : ?>
                <?= e($category->getFrontEndName()) ?>
            <?php endif ?>

            <?php $title = $repository_hierarchy->getCallNumberCategoryTitleService()->getCallNumberCategoryTitle($category->getFrontEndName(true)) ?>
			<?php if (($title !== '') && $show_titles): ?>
				(
					<?= e($title) ?>
				)
		    <?php endif ?>	
<?php endif ?>

<?php $categories = Functions::getCollectionForArray($category->getSubCategories()) ?>

<?php foreach ($categories as $sub_category) : ?>
    <?= view(RepositoryHierarchy::viewsNamespace() . '::table-of-contents', [
            'repository_hierarchy'	=> $repository_hierarchy,
            'category'              => $sub_category,
            'is_root_category'      => false,
            'show_links'			=> $show_links,
            'show_titles'			=> $show_titles,
            ]) ?>
<?php endforeach ?>

<?php if (!$is_root_category) : ?>
        </li>
    </ul>
<?php endif ?>