<?php

namespace Jefferson49\Webtrees\Module\RepositoryHierarchyNamespace;

use Cissee\WebtreesExt\MoreI18N;
use Fisharebest\Webtrees\I18N;

/**
 * @var  RepositoryHierarchy	$repository_hierarchy
 * @var  CallNumberCategory		$category
 */
?>

<div class="d-flex">
	<span class="wt-chart-horizontal-spacer d-inline-block"></span>
	<button class="btn btn-link px-0 py-1 wt-chart-expansion-control" data-bs-toggle="collapse" data-bs-target="#category_id-<?= e($category->getId()) ?>" aria-controls="category_id-<?= e($category->getId()) ?>" aria-expanded="true">
		<span class="chart-expand">
			<?= view('icons/expand') ?>
		</span>
		<span class="chart-collapse">
			<?= view('icons/collapse') ?>
		</span>

		<?php if (boolval($repository_hierarchy->getPreference($repository_hierarchy::PREF_SHOW_CATEGORY_LABEL, '1'))) : ?>
			<b><?= I18N::translate('Call Number Category') . ': ' ?></b>
		<?php endif ?>		

		<?php if (boolval($repository_hierarchy->getPreference($repository_hierarchy::PREF_SHOW_TRUNCATED_CATEGORY, '1'))) : ?>
			<b><?= e($category->getFrontEndName()) ?> </b>
		<?php else : ?>		
			<b><?= e($category->getFrontEndName(true)) ?></b>
		<?php endif ?>	

		<?php $title = $repository_hierarchy->getCallNumberCategoryTitleService()->getCallNumberCategoryTitle($category->getFrontEndName(true)) ?>
		<?php if (($title !== '') && (boolval($repository_hierarchy->getPreference($repository_hierarchy::PREF_SHOW_CATEGORY_TITLE, '0')))): ?>
			(
				<?= e($title) ?>
			)
		<?php endif ?>		

		<?php if (($category->getOverallDateRange() !== null) && (boolval($repository_hierarchy->getPreference($repository_hierarchy::PREF_SHOW_DATE_RANGE_FOR_CATEGORY, '0')))) : ?>
			—
			<?= MoreI18N::xlate('Date range') ?>:
			<?php //Do not escape, because it is already escaped in the method  ?>
			<?= $category->getOverallDateRange()->display() ?>
		<?php endif ?>
	</button>			
	<?= view('icons/spacer') ?>
	<?php if ((strpos($category->getFullName(), CallNumberCategory::EMPTY_CATEGORY_NAME) === false) and (strpos($category->getFullName(), CallNumberCategory::DEFAULT_CATEGORY_NAME) === false)) : ?>
		<button class="btn btn-link px-0 py-1 wt-chart-expansion-control" aria-expanded="true">
			<?php if (boolval($repository_hierarchy->getPreference($repository_hierarchy::PREF_ALLOW_RENAME, '1'))) : ?>
				<a href="<?= e(route(CallNumberDataFix::class, [
                        'tree' => $repository_hierarchy->getTree()->name(),
                        'xref' => $repository_hierarchy->getRepositoryXref(),
                        'category_name' => $category->getName(),
                        'category_full_name' => $category->getFullName()
                        ])) ?>">
					<?= view('icons/edit') ?>
					<?= I18N::translate('Rename') ?>	
				</a>
				<?= view('icons/spacer') ?>
			<?php endif ?>	
			<?php if (boolval($repository_hierarchy->getPreference($repository_hierarchy::PREF_ALLOW_NEW_SOURCE, '1'))) : ?>
				<a href="#" data-bs-toggle="modal" data-bs-backdrop="static" data-bs-target="#wt-ajax-modal" 
							data-wt-href="<?= e(route(CreateSourceModal::class, [
                                'tree' => $repository_hierarchy->getTree()->name(),
                                'xref' => $repository_hierarchy->getRepositoryXref(),
                                'source_call_number' => $category->getFullName(),
                                ])) ?>">
					<?= view('icons/source') ?>
					<?= I18N::translate('Add new source') ?>	
				</a>
			<?php endif ?>		
		</button>
	<?php endif ?>		
</div>
<div id="category_id-<?= e($category->getId()) ?>" class="collapse show mb-4">
	<div class="d-flex">
		<div class="wt-chart-horizontal-indent position-relative">
		</div>
		<div>
			<div class="d-flex">	
				<ul>
					<?php $sources = Functions::getCollectionForArray($category->getSources()) ?>
            		<?php $sources = $repository_hierarchy->sortSourcesByCallNumber($sources) ?>
					<?php foreach ($sources as $source) : ?>
						<li>
							<?php if(boolval($repository_hierarchy->getPreference($repository_hierarchy::PREF_SHOW_TRUNCATED_CALL_NUMBER, '1'))): ?>
								<a href="<?= e($source->url()) ?>"><?= e($category->getTruncatedCallNumber($source)) ?></a>
							<?php else : ?>
								<a href="<?= e($source->url()) ?>"><?= e($repository_hierarchy->call_number_of_source[$source->xref()]) ?></a>
							<?php endif ?>

							<?php if (($source->fullName() != '') && (boolval($repository_hierarchy->getPreference($repository_hierarchy::PREF_SHOW_TITLE, '1')))) : ?>
								—
								<?= MoreI18N::xlate('Title') ?>:						
								<a href="<?= e($source->url()) ?>">
									<?php //Do not escape, because it is already escaped in the method  ?>
									<?= $source->fullName() ?>				
								</a>
							<?php endif ?>

							<?php if (boolval($repository_hierarchy->getPreference($repository_hierarchy::PREF_SHOW_XREF, '1'))) : ?>							
								—
								<a href="<?= e($source->url()) ?>">	
									<?= e('('. $source->xref() . ')') ?>
								</a>
							<?php endif ?>							

							<?php if (($source->facts(['AUTH'])->isNotEmpty()) && (boolval($repository_hierarchy->getPreference($repository_hierarchy::PREF_SHOW_AUTHOR, '1')))) : ?>
								—
								<?= I18N::translate('Author') ?>:
								<?= e($source->facts(['AUTH'])->first()->value()) ?>
							<?php endif ?>	

							<?php if (isset($repository_hierarchy->date_range_text_of_source[$source->xref()]) && (boolval($repository_hierarchy->getPreference($repository_hierarchy::PREF_SHOW_DATE_RANGE, '1')))) : ?>
								—
								<?= MoreI18N::xlate('Date range') ?>:
								<?php //Do not escape, because it is already escaped in the method  ?>
								<?= $repository_hierarchy->date_range_text_of_source[$source->xref()] ?>
							<?php endif ?>
						</li>
					<?php endforeach ?>	
				</ul>
			</div>

			<?php $categories = Functions::getCollectionForArray($category->getSubCategories()) ?>
			<?php $categories = CallNumberCategory::sortCallNumberCategoriesByName($categories) ?>
			<?php foreach ($categories as $sub_category) : ?>			
				<?= view(RepositoryHierarchy::viewsNamespace() . '::tree', [
                    'repository_hierarchy' => $repository_hierarchy,
                    'category' => $sub_category]) ?>
			<?php endforeach ?>	
		</div>	
	</div>
</div>	
    