<?php

declare(strict_types=1);

namespace Jefferson49\Webtrees\Module\RepositoryHierarchy;

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;

/**
 * @var Tree    $tree
 * @var string  $xref
 * @var string  $gedcom
 */

?>

<a class="btn btn-link btn-sm" href="#" data-wt-post-url="
    <?= e(route(CopySourceCitation::class, [
        'tree'    => $tree->name(),
        'gedcom'  => $gedcom,
    ])) ?>" title="<?= I18N::translate('Copy source citation to clipboard') ?>">
    
    <?= view('icons/copy') ?>
    <span class="visually-hidden"><?= I18N::translate('Copy source citation to clipboard') ?></span>
</a>