<?php

namespace Jefferson49\Webtrees\Module\RepositoryHierarchyNamespace;

use Fisharebest\Webtrees\Http\RequestHandlers\CreateSourceAction;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;

/**
 * @var Tree	$tree
 * @var string	$source_repository
 * @var string	$source_call_number
 */

?>

<form method="post" action="<?= e(route(CreateSourceAction::class, [
			'tree' 					=> $tree->name(),
			'source-repository' 	=> $source_repository,
			'source-call-number' 	=> $source_call_number,
        ])) ?>" id="wt-modal-form">
    <?= view('modals/header', ['title' => I18N::translate('Create a source')]) ?>

    <div class="modal-body">
        <?= view(RepositoryHierarchy::MODULE_NAME . '::modals/source-fields', [
            'tree' 					=> $tree,
            'source_repository' 	=> $source_repository,
            'source_call_number'	=> $source_call_number,
        ]) ?>
    </div>

    <?= view('modals/footer-save-cancel') ?>

    <?= csrf_field() ?>
</form>

<script>
  document.getElementById('wt-modal-form').addEventListener('submit', webtrees.createRecordModalSubmit);
</script>
