<?php

use Cissee\WebtreesExt\MoreI18N;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Registry;
use Fisharebest\Webtrees\Tree;

/**
 * @var Tree   $tree
 * @var string $source_repository
 * @var string $source_call_number
 */

?>

<div class="row mb-3">
    <label class="col-form-label col-sm-2" for="source-title">
        <?= MoreI18N::xlate('Title') ?>
    </label>
    <div class="col-sm-10">
        <input class="form-control" type="text" id="source-title" name="source-title" required="required">
    </div>
</div>
<div class="row mb-3">
    <label class="col-form-label col-sm-2" for="source-abbreviation">
        <?= MoreI18N::xlate('Abbreviation') ?>
    </label>
    <div class="col-sm-10">
        <input class="form-control" type="text" id="source-abbreviation" name="source-abbreviation">
    </div>
</div>
<div class="row mb-3">
    <label class="col-form-label col-sm-2" for="source-author">
        <?= MoreI18N::xlate('Author') ?>
    </label>
    <div class="col-sm-4">
        <input class="form-control" type="text" id="source-author" name="source-author">
    </div>
    <label class="col-form-label col-sm-2" for="source-publication">
        <?= MoreI18N::xlate('Publication') ?>
    </label>
    <div class="col-sm-4">
        <input class="form-control" type="text" id="source-publication" name="source-publication">
    </div>
</div>
<div class="row mb-3">
    <label class="col-form-label col-sm-2" for="source-repository">
        <?= MoreI18N::xlate('Repository') ?>
    </label>
    <div class="col-sm-4">
        <?= view('components/select-repository', ['name' => 'source-repository', 'tree' => $tree, 'repository' => Registry::repositoryFactory()->make($source_repository, $tree)]) ?>
    </div>
    <label class="col-form-label col-sm-2" for="source-call-number">
        <?= MoreI18N::xlate('Call number') ?>
    </label>
    <div class="col-sm-4">
        <input class="form-control" type="text" id="source-call-number" name="source-call-number" value = "<?= $source_call_number . '{' . I18N::translate('new') . '}' ?>" >
    </div>
</div>
<div class="row mb-3">
    <label class="col-form-label col-sm-2" for="source-text">
        <?= MoreI18N::xlate('Text') ?>
    </label>
    <div class="col-sm-10">
        <textarea class="form-control" id="source-text" name="source-text" rows="5"></textarea>
    </div>
</div>

<?= view('modals/restriction-fields') ?>
