<?php

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;

/**
 * @var Tree 	$tree
 * @var string 	$xref
 * @var string 	$main_agency_code
 * @var string 	$country_code
 */

?>

<div class="row mb-3">
    <label class="col-form-label col-sm-2" for="main_agency_code">
        <?= I18N::translate('Main agency code') ?>
    </label>
    <div class="col-sm-10">
        <input class="form-control" type="text" id="main_agency_code" name="main_agency_code" value="<?= $main_agency_code ?>" required="required">
    </div>
</div>
<div class="row mb-3">
    <label class="col-form-label col-sm-2" for="country_code">
        <?= I18N::translate('Country code') ?>
    </label>
    <div class="col-sm-10">
        <input class="form-control" type="text" id="country_code" name="country_code" value="<?= $country_code ?>" required="required">
    </div>
</div>
<div class="visually-hidden">
    <label class="col-sm-3 col-form-label" for="xref">
        <?= I18N::translate('Repository') ?>
    </label>

    <div class="col-sm-9">
        <input class="form-control" id="xref" name="xref" value="<?= e($xref) ?>">
    </div>
</div>

